
PRIMARY_RED = "#D81F27"
PRIMARY_RED_HOVER = "#B01821"
PRIMARY_RED_LIGHT = "#FBE9EA"

BACKGROUND_LIGHT = "#F6F6F6"
SURFACE_WHITE = "#FFFFFF"
BORDER_LIGHT = "#E3E3E3"

TEXT_DARK = "#2B2B2B"
TEXT_MUTED = "#6E6E6E"
TEXT_ON_PRIMARY = "#FFFFFF"

SIDEBAR_BG = "#2C2C2C"
SIDEBAR_BG_HOVER = "#3D3D3D"
SIDEBAR_TEXT = "#F2F2F2"
SIDEBAR_TEXT_DISABLED = "#8A8A8A"
SIDEBAR_SELECTED = "#D81F27"

BUBBLE_USER_BG = PRIMARY_RED
BUBBLE_USER_TEXT = "#FFFFFF"
BUBBLE_AI_BG = "#EFEFEF"
BUBBLE_AI_TEXT = "#2B2B2B"

STATUS_GREEN = "#1F9D55"
STATUS_YELLOW = "#D9A400"
STATUS_RED = "#E5484D"

STATUS_GREEN_BG = "#EAF3DE"
STATUS_GREEN_TEXT = "#27500A"
STATUS_NEUTRAL_BG = "#F1EFE8"
STATUS_NEUTRAL_TEXT = "#5F5E5A"

FONT_FAMILY = "Segoe UI"
FONT_SIZE_TITLE = 16
FONT_SIZE_NORMAL = 13
FONT_SIZE_SMALL = 11

CORNER_RADIUS = 12
